Added SEA
sei-protocol/chain-registry pull request #14
Opened 2023-08-14 15:34 UTC by Nova-Ratio

2023-08-15 13:18 UTC, besated requested changes

2023-08-15 13:18 UTC, besated commented on assetlist.json
> +        "png": "ipfs://bafybeienvbj5vmecuiamsqob6newo4mpeudzur7qml7jtc5bscjkqrdkuq/sea-token.png"
do you have this hosted on a cdn or another location that's not ipfs? i believe apis that are using this registry are expecting a link to an image and aren't configured to handle IPFS image urls just yet

2023-08-16 13:59 UTC, Nova-Ratio commented on assetlist.json
> +        "png": "ipfs://bafybeienvbj5vmecuiamsqob6newo4mpeudzur7qml7jtc5bscjkqrdkuq/sea-token.png"
it's done, sir

2023-08-24 16:55 UTC, besated approved these changes

2023-08-24 22:17 UTC, merged