Add Kava Mainnet to ibc_info
sei-protocol/chain-registry pull request #23
Opened 2023-10-23 18:47 UTC by samcode206

2023-10-24 19:08 UTC, LCyson requested changes
@samcode206 ser can you also add asset metadata to here https://github.com/sei-protocol/chain-registry/blob/main/assetlist.json#L2

2023-10-24 19:08 UTC, LCyson commented on ibc_info.json
> +      "src_channel": "channel-8",
src_channel doesn't match with what's written here (channel-18) https://github.com/sei-protocol/chain-registry/blob/main/assetlist.json, can you double check?

2023-11-08 17:29 UTC, besated requested changes
Thanks for making this pr! I left a comment, please take a look and let me know if you have any questions

2023-11-08 17:29 UTC, besated commented on assetlist.json
> +      "display": "USD₮",
The display denom here should match one of the denoms in `denom_units`. I suggest updating `erc20/tether/usdt` to `USD₮` in `denom_units` below

2023-11-15 17:31 UTC, samcode206 commented on assetlist.json
> +      "display": "USD₮",
I don't think `USD₮` is a denom unit it's just a display name, would that have any consequences or is it safe to change it still ?

2023-11-15 22:33 UTC, besated commented on assetlist.json
> +      "display": "USD₮",
It should be safe to change. The display field should match with one of the denoms in `denom_units`, and it's mainly used for determining the appropriate number of decimals/exponents to use for user interfaces and readability. It does not necessarily have to correspond to a transferrable denom. This aligns with the standards from the Cosmos chain registry

2023-12-13 17:40 UTC, closed without merging